"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

										1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

import sys

def main():
	fib1 = fib2 = 1
	a = []

	n = 10

	for i in range(1, n):
		fib1, fib2 = fib2, fib1 + fib2
#		print(fib2, end=' ')
		a.append(fib2)
#		print(a)
	
	thesum = 0
	if fib2 % 2 == 0:
		for i in a:
			thesum += i
		return thesum

if __name__ == "__main__":
	main()